# This is a basic workflow poking me each day at a regular time to 
# fill my wilt of the day

name: wilt-daily

on:
  workflow_dispatch:
  schedule:
  - cron: "0 20 * * *"

jobs:
  pr_reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - uses: actions/checkout@v2

      - name: Insert new date
        env:
          DATE: ${{steps.date.outputs.date}}
        run: |
          echo "" >> README.md
          echo "# $DATE" >> README.md
          echo "->write your learnings here<-" >> README.md
          echo "" >> README.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          assignees: michelml
          committer: MichelML <michmoreau.l@gmail.com>
          author: MichelML <michmoreau.l@gmail.com>
          title: "Daily WILT ${{steps.date.outputs.date}}"
          body: "@MichelML, time to add your learnings of the day!"
          commit-message: "Daily WILT ${{steps.date.outputs.date}}"
          delete-branch: True
          
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.WILT_GH_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
